### ISSUE TITLE
Tests are failing.

### ISSUE THREAD

**Issue by ronanyeah** [mohanagy/iLearn#10]

**Comment by mohanagy** [comment]
[fixed](https://github.com/mohanagy/iLearn/commit/d7a34a82d0cf32308fd6d9a12294ac2c993e283a#diff-86b7ab329b7d2ddc8c69e85c3a9a0d71)

**Comment by mohanagy** [comment]
[fixed](https://github.com/mohanagy/iLearn/commit/3cc8ea4c216d84e7b0a722fc03691db260b8f247)
