### ISSUE TITLE
Unnecessary packages.

### ISSUE THREAD

**Issue by ronanyeah** [mohanagy/iLearn#12]
"babel-cli": "^6.24.0",
    "babel-preset-stage-2": "^6.22.0",
    "handlebars": "^4.0.6",
    "react-hot-loader": "^1.3.1",
    "redux-async": "^2.0.1",
    "vision": "^4.1.1",
    "babel-preset-es2015": "^6.24.0",

There is also several packages in both dependencies and devDeps.

**Comment by mohanagy** [comment]
[fixed](https://github.com/mohanagy/iLearn/commit/1e76c6e46d9212f98a48b42901aea48513226006)
