### ISSUE TITLE
What

### ISSUE THREAD

**Issue by ronanyeah** [mohanagy/iLearn#13]
https://github.com/mohanagy/iLearn/blob/master/.eslintignore#L2

**Comment by mohanagy** [comment]
it just comment mean that the igonare for the next file is temp

**Comment by ronanyeah** [comment]
Get rid of it :smile:

**Comment by mohanagy** [comment]
[fixed](https://github.com/mohanagy/iLearn/commit/f22c50927f070e81377de08ae6bcbd11227a40ee#diff-1b0fd5322de42e11c8786543f74c7c41)
