### ISSUE TITLE
Too many Eslint disable

### ISSUE THREAD

**Issue by ronanyeah** [mohanagy/iLearn#15]
Change the rule in your config to not check parameters. If eslint is being too strict, change a rule.
https://github.com/mohanagy/iLearn/blob/master/src/server/server.js#L1
http://eslint.org/docs/rules/no-unused-vars

**Comment by mohanagy** [comment]
[fixed](https://github.com/mohanagy/iLearn/commit/5b70c6b148eb88bf325e6363b83482be20786277)

**Comment by ronanyeah** [comment]
`no-unused-vars: ["error", { "args": "none" }]`

**Comment by mohanagy** [comment]
[fix](https://github.com/mohanagy/iLearn/commit/f22c50927f070e81377de08ae6bcbd11227a40ee#diff-e4403a877d80de653400d88d85e4801a)

**Comment by mohanagy** [comment]
fixed
