### ISSUE TITLE
eslint disable

### ISSUE THREAD

**Issue by ronanyeah** [mohanagy/iLearn#4]
https://github.com/mohanagy/iLearn/blob/master/src/client/index.jsx#L11
nice usage, but its good to also specify what rule you are disabling
for example `// eslint-disable-next-line no-console`

**Comment by mohanagy** [comment]
no-console its reffer to a rule called no console 
there is no rule called no document 
if i added custom rule , its will faild 
check the image 
![image](https://cloud.githubusercontent.com/assets/11216054/24795364/ca2d310a-1b91-11e7-84ff-7b720b49e3d6.png)
and you can check the rule  through this link
[List of eslint rules](http://eslint.org/docs/rules/)

**Comment by ronanyeah** [comment]
it's probably a react rule. look at what your linter is saying to find out what rule is failing

**Comment by mohanagy** [comment]
its said the same problem before adding the line number 12 
after 
![image](https://cloud.githubusercontent.com/assets/11216054/24795623/9df3078a-1b92-11e7-8d1c-2a6e957ce5cc.png)

before 
![image](https://cloud.githubusercontent.com/assets/11216054/24795658/c5684e38-1b92-11e7-80c1-0016ea5e1ada.png)

**Comment by ronanyeah** [comment]
interesting. document should be a browser global.
http://eslint.org/docs/user-guide/configuring.html#specifying-environments
you already have `shared-node-browser` in your eslint file which should enable browser globals.
ok leave it for now :+1:

**Comment by mohanagy** [comment]
:+1:
