### ISSUE TITLE
massive component

### ISSUE THREAD

**Issue by ronanyeah** [mohanagy/iLearn#7]
https://github.com/mohanagy/iLearn/blob/master/src/client/LearnList.jsx#L1
this should be split into two components immediately.
1. a form component with state for the text input areas.
2. a STATELESS component for displaying the list.

please ask any questions on gitter if you have them

**Comment by mohanagy** [comment]
[fix it](https://github.com/mohanagy/iLearn/commit/148dc05fb938d48c879861380c4a606c6062299c)
:+1:
