### ISSUE TITLE
createClass is deprecated.

### ISSUE THREAD

**Issue by ronanyeah** [mohanagy/iLearn#9]
I'm gettting an error in my console about this.
https://github.com/mohanagy/iLearn/blob/master/src/client/label.jsx#L3

**Comment by mohanagy** [comment]
screenshot the error please

**Comment by ronanyeah** [comment]
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by mohanagy** [comment]
[fixed](https://github.com/mohanagy/iLearn/commit/f22c50927f070e81377de08ae6bcbd11227a40ee#diff-30dcccb3e0154d107457957814115ada)
